// <auto-generated />
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.

namespace MagicOnion
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::MagicOnion;
    using global::MagicOnion.Client;

    public static partial class MagicOnionInitializer
    {
        static bool isRegistered = false;

#if UNITY_2019_4_OR_NEWER
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]
#elif NET5_0_OR_GREATER
        [System.Runtime.CompilerServices.ModuleInitializer]
#endif
        public static void Register()
        {
            if (isRegistered) return;
            isRegistered = true;

            global::MagicOnion.Client.MagicOnionClientFactoryProvider.Default =
                (global::MagicOnion.Client.MagicOnionClientFactoryProvider.Default is global::MagicOnion.Client.ImmutableMagicOnionClientFactoryProvider immutableMagicOnionClientFactoryProvider)
                    ? immutableMagicOnionClientFactoryProvider.Add(MagicOnionGeneratedClientFactoryProvider.Instance)
                    : new global::MagicOnion.Client.ImmutableMagicOnionClientFactoryProvider(MagicOnionGeneratedClientFactoryProvider.Instance);

            global::MagicOnion.Client.StreamingHubClientFactoryProvider.Default =
                (global::MagicOnion.Client.StreamingHubClientFactoryProvider.Default is global::MagicOnion.Client.ImmutableStreamingHubClientFactoryProvider immutableStreamingHubClientFactoryProvider)
                    ? immutableStreamingHubClientFactoryProvider.Add(MagicOnionGeneratedClientFactoryProvider.Instance)
                    : new global::MagicOnion.Client.ImmutableStreamingHubClientFactoryProvider(MagicOnionGeneratedClientFactoryProvider.Instance);
        }
    }

    public partial class MagicOnionGeneratedClientFactoryProvider : global::MagicOnion.Client.IMagicOnionClientFactoryProvider, global::MagicOnion.Client.IStreamingHubClientFactoryProvider
    {
        public static MagicOnionGeneratedClientFactoryProvider Instance { get; } = new MagicOnionGeneratedClientFactoryProvider();

        MagicOnionGeneratedClientFactoryProvider() {}

        bool global::MagicOnion.Client.IMagicOnionClientFactoryProvider.TryGetFactory<T>(out global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T> factory)
            => (factory = MagicOnionClientFactoryCache<T>.Factory) != null;

        bool global::MagicOnion.Client.IStreamingHubClientFactoryProvider.TryGetFactory<TStreamingHub, TReceiver>(out global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver> factory)
            => (factory = StreamingHubClientFactoryCache<TStreamingHub, TReceiver>.Factory) != null;

        static class MagicOnionClientFactoryCache<T> where T : global::MagicOnion.IService<T>
        {
            public readonly static global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T> Factory;

            static MagicOnionClientFactoryCache()
            {
                object factory = default(global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T>);

                Factory = (global::MagicOnion.Client.MagicOnionClientFactoryDelegate<T>)factory;
            }
        }
        
        static class StreamingHubClientFactoryCache<TStreamingHub, TReceiver> where TStreamingHub : global::MagicOnion.IStreamingHub<TStreamingHub, TReceiver>
        {
            public readonly static global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver> Factory;

            static StreamingHubClientFactoryCache()
            {
                object factory = default(global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver>);

                if (typeof(TStreamingHub) == typeof(global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender) && typeof(TReceiver) == typeof(global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Receiver.IOrtegaReceiver))
                {
                    factory = ((global::MagicOnion.Client.StreamingHubClientFactoryDelegate<global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender, global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Receiver.IOrtegaReceiver>)((a, _, b, c, d, e) => new MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.OrtegaSenderClient(a, b, c, d, e)));
                }

                Factory = (global::MagicOnion.Client.StreamingHubClientFactoryDelegate<TStreamingHub, TReceiver>)factory;
            }
        }
    }

}

#pragma warning restore 168
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 612
#pragma warning restore 618

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.
namespace MagicOnion.Resolvers
{
    using global::System;
    using global::MessagePack;

    partial class PreserveAttribute : global::System.Attribute {}
    public class MagicOnionResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new MagicOnionResolver();
    
        MagicOnionResolver() {}
    
        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
            => FormatterCache<T>.formatter;
    
        static class FormatterCache<T>
        {
            public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> formatter;
    
            static FormatterCache()
            {
                var f = MagicOnionResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }
    internal static class MagicOnionResolverGetFormatterHelper
    {
        static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;
    
        static MagicOnionResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(1)
            {
                {typeof(global::MementoMori.Ortega.Share.ErrorCode), 0 },
            };
        }
        internal static object GetFormatter(Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }
        
            switch (key)
            {
                case 0: return new MagicOnion.Formatters.ErrorCodeFormatter();
                default: return null;
            }
        }
    }
    /// <summary>Type hints for Ahead-of-Time compilation.</summary>
    [MagicOnion.Resolvers.Preserve]
    internal static class TypeHints
    {
        [MagicOnion.Resolvers.Preserve]
        internal static void Register()
        {
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.ErrorCode>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnAddOnlyReceiverPartyResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnEndCastleBattleResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnGetRoomListResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnInviteResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnJoinRoomResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnNoticePrivateMessageResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnOpenBattleDialogResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveGuildChatLogResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveMessageResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveSvSChatLogResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveWorldChatLogResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateCastlePartyResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateDeployCharacterResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateMapResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdatePartyCountResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateRoomResponse>();
            _ = MagicOnionResolver.Instance.GetFormatter<global::MessagePack.Nil>();
        }
    }
}
#pragma warning restore 168
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 612
#pragma warning restore 618

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

namespace MagicOnion.Formatters
{
    using System;
    using MessagePack;

    public sealed class ErrorCodeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::MementoMori.Ortega.Share.ErrorCode>
    {
        public void Serialize(ref MessagePackWriter writer, global::MementoMori.Ortega.Share.ErrorCode value, MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }
        
        public global::MementoMori.Ortega.Share.ErrorCode Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
        {
            return (global::MementoMori.Ortega.Share.ErrorCode)reader.ReadInt32();
        }
    }

}

#pragma warning restore 168
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 612
#pragma warning restore 618
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.


#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.

namespace MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender
{
    using global::System;
    using global::Grpc.Core;
    using global::MagicOnion;
    using global::MagicOnion.Client;
    using global::MessagePack;
    
    [global::MagicOnion.Ignore]
    public class OrtegaSenderClient : global::MagicOnion.Client.StreamingHubClientBase<global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender, global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Receiver.IOrtegaReceiver>, global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender
    {
        protected override global::Grpc.Core.Method<global::System.Byte[], global::System.Byte[]> DuplexStreamingAsyncMethod { get; }
        
        public OrtegaSenderClient(global::Grpc.Core.CallInvoker callInvoker, global::System.String host, global::Grpc.Core.CallOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider, global::MagicOnion.Client.IMagicOnionClientLogger logger)
            : base(callInvoker, host, options, serializerProvider, logger)
        {
            var marshaller = global::MagicOnion.MagicOnionMarshallers.ThroughMarshaller;
            DuplexStreamingAsyncMethod = new global::Grpc.Core.Method<global::System.Byte[], global::System.Byte[]>(global::Grpc.Core.MethodType.DuplexStreaming, "IOrtegaSender", "Connect", marshaller, marshaller);
        }
        
        public global::System.Threading.Tasks.Task AuthenticateAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest, global::MessagePack.Nil>(-923466704, request);
        public global::System.Threading.Tasks.Task KeepAliveAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1790563379, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task DisbandRoomAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-557824115, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task GetRoomListAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest, global::MessagePack.Nil>(-24868804, request);
        public global::System.Threading.Tasks.Task InviteAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest, global::MessagePack.Nil>(470708468, request);
        public global::System.Threading.Tasks.Task JoinFriendRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest, global::MessagePack.Nil>(-172377630, request);
        public global::System.Threading.Tasks.Task JoinRandomRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest, global::MessagePack.Nil>(897853063, request);
        public global::System.Threading.Tasks.Task JoinRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest, global::MessagePack.Nil>(464561018, request);
        public global::System.Threading.Tasks.Task LeaveRoomAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1964019333, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task OpenRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest, global::MessagePack.Nil>(1454231306, request);
        public global::System.Threading.Tasks.Task RefuseAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest, global::MessagePack.Nil>(-2109548737, request);
        public global::System.Threading.Tasks.Task ReadyAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest, global::MessagePack.Nil>(470601768, request);
        public global::System.Threading.Tasks.Task UpdateBattlePowerAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest, global::MessagePack.Nil>(-1004345023, request);
        public global::System.Threading.Tasks.Task UpdateRoomConditionAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest, global::MessagePack.Nil>(-1076165108, request);
        public global::System.Threading.Tasks.Task StartBattleAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-1717742521, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task UpdatePartyCountAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-2004987623, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task RoomClearAsync()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(298875301, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task SendMessageAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest, global::MessagePack.Nil>(-601690414, request);
        public global::System.Threading.Tasks.Task LocalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest, global::MessagePack.Nil>(44650903, request);
        public global::System.Threading.Tasks.Task LocalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest, global::MessagePack.Nil>(1668024442, request);
        public global::System.Threading.Tasks.Task LocalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest, global::MessagePack.Nil>(1986037168, request);
        public global::System.Threading.Tasks.Task LocalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest, global::MessagePack.Nil>(-1904399543, request);
        public global::System.Threading.Tasks.Task LocalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest, global::MessagePack.Nil>(1458900826, request);
        public global::System.Threading.Tasks.Task LocalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest, global::MessagePack.Nil>(-2110597634, request);
        public global::System.Threading.Tasks.Task LocalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest, global::MessagePack.Nil>(1854613006, request);
        public global::System.Threading.Tasks.Task LocalGvgOpenMap()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1629081364, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task LocalGvgCloseMap()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(50244984, global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task GlobalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest, global::MessagePack.Nil>(1863603745, request);
        public global::System.Threading.Tasks.Task GlobalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest, global::MessagePack.Nil>(-204081408, request);
        public global::System.Threading.Tasks.Task GlobalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest, global::MessagePack.Nil>(-929378510, request);
        public global::System.Threading.Tasks.Task GlobalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest, global::MessagePack.Nil>(712299371, request);
        public global::System.Threading.Tasks.Task GlobalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest, global::MessagePack.Nil>(-767373952, request);
        public global::System.Threading.Tasks.Task GlobalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest, global::MessagePack.Nil>(1811427008, request);
        public global::System.Threading.Tasks.Task GlobalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest, global::MessagePack.Nil>(884516, request);
        public global::System.Threading.Tasks.Task GlobalGvgOpenMap(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest request)
            => base.WriteMessageWithResponseAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest, global::MessagePack.Nil>(1164177054, request);
        public global::System.Threading.Tasks.Task GlobalGvgCloseMap()
            => base.WriteMessageWithResponseAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-614570070, global::MessagePack.Nil.Default);
        
        public global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender FireAndForget()
            => new FireAndForgetClient(this);
        
        [global::MagicOnion.Ignore]
        class FireAndForgetClient : global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender
        {
            readonly OrtegaSenderClient parent;
        
            public FireAndForgetClient(OrtegaSenderClient parent)
                => this.parent = parent;
        
            public global::MementoMori.Ortega.Share.MagicOnionShare.Interfaces.Sender.IOrtegaSender FireAndForget() => this;
            public global::System.Threading.Tasks.Task DisposeAsync() => throw new global::System.NotSupportedException();
            public global::System.Threading.Tasks.Task WaitForDisconnect() => throw new global::System.NotSupportedException();
        
            public global::System.Threading.Tasks.Task AuthenticateAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest, global::MessagePack.Nil>(-923466704, request);
            public global::System.Threading.Tasks.Task KeepAliveAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1790563379, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task DisbandRoomAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-557824115, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task GetRoomListAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest, global::MessagePack.Nil>(-24868804, request);
            public global::System.Threading.Tasks.Task InviteAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest, global::MessagePack.Nil>(470708468, request);
            public global::System.Threading.Tasks.Task JoinFriendRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest, global::MessagePack.Nil>(-172377630, request);
            public global::System.Threading.Tasks.Task JoinRandomRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest, global::MessagePack.Nil>(897853063, request);
            public global::System.Threading.Tasks.Task JoinRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest, global::MessagePack.Nil>(464561018, request);
            public global::System.Threading.Tasks.Task LeaveRoomAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1964019333, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task OpenRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest, global::MessagePack.Nil>(1454231306, request);
            public global::System.Threading.Tasks.Task RefuseAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest, global::MessagePack.Nil>(-2109548737, request);
            public global::System.Threading.Tasks.Task ReadyAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest, global::MessagePack.Nil>(470601768, request);
            public global::System.Threading.Tasks.Task UpdateBattlePowerAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest, global::MessagePack.Nil>(-1004345023, request);
            public global::System.Threading.Tasks.Task UpdateRoomConditionAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest, global::MessagePack.Nil>(-1076165108, request);
            public global::System.Threading.Tasks.Task StartBattleAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-1717742521, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task UpdatePartyCountAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-2004987623, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task RoomClearAsync()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(298875301, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task SendMessageAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest, global::MessagePack.Nil>(-601690414, request);
            public global::System.Threading.Tasks.Task LocalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest, global::MessagePack.Nil>(44650903, request);
            public global::System.Threading.Tasks.Task LocalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest, global::MessagePack.Nil>(1668024442, request);
            public global::System.Threading.Tasks.Task LocalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest, global::MessagePack.Nil>(1986037168, request);
            public global::System.Threading.Tasks.Task LocalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest, global::MessagePack.Nil>(-1904399543, request);
            public global::System.Threading.Tasks.Task LocalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest, global::MessagePack.Nil>(1458900826, request);
            public global::System.Threading.Tasks.Task LocalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest, global::MessagePack.Nil>(-2110597634, request);
            public global::System.Threading.Tasks.Task LocalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest, global::MessagePack.Nil>(1854613006, request);
            public global::System.Threading.Tasks.Task LocalGvgOpenMap()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1629081364, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task LocalGvgCloseMap()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(50244984, global::MessagePack.Nil.Default);
            public global::System.Threading.Tasks.Task GlobalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest, global::MessagePack.Nil>(1863603745, request);
            public global::System.Threading.Tasks.Task GlobalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest, global::MessagePack.Nil>(-204081408, request);
            public global::System.Threading.Tasks.Task GlobalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest, global::MessagePack.Nil>(-929378510, request);
            public global::System.Threading.Tasks.Task GlobalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest, global::MessagePack.Nil>(712299371, request);
            public global::System.Threading.Tasks.Task GlobalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest, global::MessagePack.Nil>(-767373952, request);
            public global::System.Threading.Tasks.Task GlobalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest, global::MessagePack.Nil>(1811427008, request);
            public global::System.Threading.Tasks.Task GlobalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest, global::MessagePack.Nil>(884516, request);
            public global::System.Threading.Tasks.Task GlobalGvgOpenMap(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest request)
                => parent.WriteMessageFireAndForgetAsync<global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest, global::MessagePack.Nil>(1164177054, request);
            public global::System.Threading.Tasks.Task GlobalGvgCloseMap()
                => parent.WriteMessageFireAndForgetAsync<global::MessagePack.Nil, global::MessagePack.Nil>(-614570070, global::MessagePack.Nil.Default);
            
        }
        
        protected override void OnBroadcastEvent(global::System.Int32 methodId, global::System.ArraySegment<global::System.Byte> data)
        {
            switch (methodId)
            {
                case -80358472: // Void OnAuthenticateSuccess()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnAuthenticateSuccess();
                    }
                    break;
                case 47121366: // Void OnError(global::MementoMori.Ortega.Share.ErrorCode errorCode)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.ErrorCode>(data);
                        receiver.OnError(value);
                    }
                    break;
                case -1851486988: // Void OnDisbandRoom()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnDisbandRoom();
                    }
                    break;
                case 998292671: // Void OnGetRoomList(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnGetRoomListResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnGetRoomListResponse>(data);
                        receiver.OnGetRoomList(value);
                    }
                    break;
                case -2144044989: // Void OnJoinRoom(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnJoinRoomResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnJoinRoomResponse>(data);
                        receiver.OnJoinRoom(value);
                    }
                    break;
                case -1549868519: // Void OnInvite(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnInviteResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnInviteResponse>(data);
                        receiver.OnInvite(value);
                    }
                    break;
                case -2039640760: // Void OnLeaveRoom()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnLeaveRoom();
                    }
                    break;
                case -1871453440: // Void OnLockRoom()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnLockRoom();
                    }
                    break;
                case 795049100: // Void OnRefuse()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnRefuse();
                    }
                    break;
                case 1627757318: // Void OnStartBattle()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnStartBattle();
                    }
                    break;
                case 284096194: // Void OnUpdatePartyCount(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdatePartyCountResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdatePartyCountResponse>(data);
                        receiver.OnUpdatePartyCount(value);
                    }
                    break;
                case -313711058: // Void OnUpdateRoom(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateRoomResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateRoomResponse>(data);
                        receiver.OnUpdateRoom(value);
                    }
                    break;
                case 58582246: // Void OnNoticePrivateMessage(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnNoticePrivateMessageResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnNoticePrivateMessageResponse>(data);
                        receiver.OnNoticePrivateMessage(value);
                    }
                    break;
                case -708218841: // Void OnRemovedFromGuild()
                    {
                        var value = base.Deserialize<global::MessagePack.Nil>(data);
                        receiver.OnRemovedFromGuild();
                    }
                    break;
                case 529129108: // Void OnReceiveGuildChatLog(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveGuildChatLogResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveGuildChatLogResponse>(data);
                        receiver.OnReceiveGuildChatLog(value);
                    }
                    break;
                case 365814763: // Void OnReceiveSvSChatLog(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveSvSChatLogResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveSvSChatLogResponse>(data);
                        receiver.OnReceiveSvSChatLog(value);
                    }
                    break;
                case 289323233: // Void OnReceiveWorldChatLog(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveWorldChatLogResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveWorldChatLogResponse>(data);
                        receiver.OnReceiveWorldChatLog(value);
                    }
                    break;
                case 470021452: // Void OnReceiveMessage(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveMessageResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnReceiveMessageResponse>(data);
                        receiver.OnReceiveMessage(value);
                    }
                    break;
                case -1825039007: // Void OnLocalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnOpenBattleDialogResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnOpenBattleDialogResponse>(data);
                        receiver.OnLocalGvgOpenBattleDialog(value);
                    }
                    break;
                case 935195154: // Void OnLocalGvgUpdateCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateCastlePartyResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateCastlePartyResponse>(data);
                        receiver.OnLocalGvgUpdateCastleParty(value);
                    }
                    break;
                case 1811488014: // Void OnLocalGvgEndCastleBattle(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnEndCastleBattleResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnEndCastleBattleResponse>(data);
                        receiver.OnLocalGvgEndCastleBattle(value);
                    }
                    break;
                case -1260374196: // Void OnLocalGvgUpdateMap(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateMapResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateMapResponse>(data);
                        receiver.OnLocalGvgUpdateMap(value);
                    }
                    break;
                case -81458204: // Void OnLocalGvgUpdateDeployCharacter(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateDeployCharacterResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateDeployCharacterResponse>(data);
                        receiver.OnLocalGvgUpdateDeployCharacter(value);
                    }
                    break;
                case 1522698495: // Void OnLocalGvgAddOnlyReceiverParty(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnAddOnlyReceiverPartyResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnAddOnlyReceiverPartyResponse>(data);
                        receiver.OnLocalGvgAddOnlyReceiverParty(value);
                    }
                    break;
                case -651575643: // Void OnGlobalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnOpenBattleDialogResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnOpenBattleDialogResponse>(data);
                        receiver.OnGlobalGvgOpenBattleDialog(value);
                    }
                    break;
                case 1818340598: // Void OnGlobalGvgUpdateCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateCastlePartyResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateCastlePartyResponse>(data);
                        receiver.OnGlobalGvgUpdateCastleParty(value);
                    }
                    break;
                case 1528102210: // Void OnGlobalGvgEndCastleBattle(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnEndCastleBattleResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnEndCastleBattleResponse>(data);
                        receiver.OnGlobalGvgEndCastleBattle(value);
                    }
                    break;
                case 1860185240: // Void OnGlobalGvgUpdateMap(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateMapResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateMapResponse>(data);
                        receiver.OnGlobalGvgUpdateMap(value);
                    }
                    break;
                case -2081884200: // Void OnGlobalGvgUpdateDeployCharacter(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateDeployCharacterResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnUpdateDeployCharacterResponse>(data);
                        receiver.OnGlobalGvgUpdateDeployCharacter(value);
                    }
                    break;
                case -982452869: // Void OnGlobalGvgAddOnlyReceiverParty(global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnAddOnlyReceiverPartyResponse response)
                    {
                        var value = base.Deserialize<global::MementoMori.Ortega.Share.MagicOnionShare.Response.OnAddOnlyReceiverPartyResponse>(data);
                        receiver.OnGlobalGvgAddOnlyReceiverParty(value);
                    }
                    break;
            }
        }
        
        protected override void OnResponseEvent(global::System.Int32 methodId, global::System.Object taskCompletionSource, global::System.ArraySegment<global::System.Byte> data)
        {
            switch (methodId)
            {
                case -923466704: // Task AuthenticateAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AuthenticateRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1790563379: // Task KeepAliveAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -557824115: // Task DisbandRoomAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -24868804: // Task GetRoomListAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.GetRoomListRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 470708468: // Task InviteAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.InviteRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -172377630: // Task JoinFriendRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinFriendRoomRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 897853063: // Task JoinRandomRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRandomRoomRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 464561018: // Task JoinRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.JoinRoomRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1964019333: // Task LeaveRoomAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1454231306: // Task OpenRoomAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenRoomRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -2109548737: // Task RefuseAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.RefuseRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 470601768: // Task ReadyAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.ReadyRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -1004345023: // Task UpdateBattlePowerAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateBattlePowerRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -1076165108: // Task UpdateRoomConditionAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.UpdateRoomConditionRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -1717742521: // Task StartBattleAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -2004987623: // Task UpdatePartyCountAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 298875301: // Task RoomClearAsync()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -601690414: // Task SendMessageAsync(global::MementoMori.Ortega.Share.MagicOnionShare.Request.SendMessageRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 44650903: // Task LocalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1668024442: // Task LocalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1986037168: // Task LocalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -1904399543: // Task LocalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1458900826: // Task LocalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -2110597634: // Task LocalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1854613006: // Task LocalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1629081364: // Task LocalGvgOpenMap()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 50244984: // Task LocalGvgCloseMap()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1863603745: // Task GlobalGvgAddCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.AddCastlePartyRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -204081408: // Task GlobalGvgOrderCastleParty(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OrderCastlePartyRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -929378510: // Task GlobalGvgOpenBattleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenBattleDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 712299371: // Task GlobalGvgOpenPartyDeployDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenPartyDeployDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -767373952: // Task GlobalGvgCloseCastleDialog(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CloseDialogRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1811427008: // Task GlobalGvgCastleDeclaration(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 884516: // Task GlobalGvgCastleDeclarationCounter(global::MementoMori.Ortega.Share.MagicOnionShare.Request.CastleDeclarationCounterRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case 1164177054: // Task GlobalGvgOpenMap(global::MementoMori.Ortega.Share.MagicOnionShare.Request.OpenMapRequest request)
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
                case -614570070: // Task GlobalGvgCloseMap()
                    base.SetResultForResponse<global::MessagePack.Nil>(taskCompletionSource, data);
                    break;
            }
        }
        
    }
}


