//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MementoMori.WebUI.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MementoMori.WebUI.Localization.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Legend Inheritance To D Rarity 的本地化字符串。
        /// </summary>
        internal static string AutoLegendInheritance {
            get {
                return ResourceManager.GetString("AutoLegendInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Matchless Inheritance To D Rarity 的本地化字符串。
        /// </summary>
        internal static string AutoMatchlessInheritance {
            get {
                return ResourceManager.GetString("AutoMatchlessInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Info 的本地化字符串。
        /// </summary>
        internal static string CharacterInfo {
            get {
                return ResourceManager.GetString("CharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute All Actions 的本地化字符串。
        /// </summary>
        internal static string ExecuteAllQuick {
            get {
                return ResourceManager.GetString("ExecuteAllQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Output 的本地化字符串。
        /// </summary>
        internal static string ExecutionOutput {
            get {
                return ResourceManager.GetString("ExecutionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Dispatch 的本地化字符串。
        /// </summary>
        internal static string ForceDispatch {
            get {
                return ResourceManager.GetString("ForceDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Received 的本地化字符串。
        /// </summary>
        internal static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Started 的本地化字符串。
        /// </summary>
        internal static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Unlocked 的本地化字符串。
        /// </summary>
        internal static string NotUnlocked {
            get {
                return ResourceManager.GetString("NotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ongoing 的本地化字符串。
        /// </summary>
        internal static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Click Login to Use Helper 的本地化字符串。
        /// </summary>
        internal static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Actions 的本地化字符串。
        /// </summary>
        internal static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reinforce Equipment Once 的本地化字符串。
        /// </summary>
        internal static string ReinforceEquipmentOnce {
            get {
                return ResourceManager.GetString("ReinforceEquipmentOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward Medal 的本地化字符串。
        /// </summary>
        internal static string RewardMissonActivity {
            get {
                return ResourceManager.GetString("RewardMissonActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Player 的本地化字符串。
        /// </summary>
        internal static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync 的本地化字符串。
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync User Info 的本地化字符串。
        /// </summary>
        internal static string SyncUserInfo {
            get {
                return ResourceManager.GetString("SyncUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Value 的本地化字符串。
        /// </summary>
        internal static string TargetValue {
            get {
                return ResourceManager.GetString("TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tower Type 的本地化字符串。
        /// </summary>
        internal static string TowerType {
            get {
                return ResourceManager.GetString("TowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Normal Items 的本地化字符串。
        /// </summary>
        internal static string UseNormalItems {
            get {
                return ResourceManager.GetString("UseNormalItems", resourceCulture);
            }
        }
    }
}
