namespace MementoMori.Ortega.Common.Enums
{
	public enum BgmType
	{
		None,
		Title,
		OP,
		DungeonBattle,
		BountyQuest,
		LocalPvp,
		GlobalPvp,
		LocalRaid,
		TowerBattle,
		Battle,
		GachaDraw,
		MemoryNormal,
		MemoryDark,
		MemoryBright,
		Gvg,
		AutoBattle,
		TitleUS,
		BattleQlipha,
		BattlePvp,
		BattleDungeonAndLocalRaid,
		MemoryFun,
		MemorySad,
		MemoryFunSparse,
		GuildTower,
		RentalRaid,
		PopularityVote = 28,
		EventTitle = 1001,
		AmbBountyQuest = 901,
		AmbLocalPvp,
		AmbGlobalPvp,
		AmbLocalRaid,
		AmbTowerBattle,
		CharacterMainSong = 9001,
		ScenarioCharacterSong,
		QliphaSong,
		Monologue,
		NewCharacter,
		CharacterDetail,
		PickupGacha,
		PlayList,
		RankingCharacterSong,
		EventPortalCharacterSong,
		PopularityVoteCharacterSong,
		TitleCharacterSong
	}
}
