namespace MementoMori.Ortega.Common.Enums;

public enum SeType
{
    None,
    CommonButton = 1001,
    CommonCancelButton,
    CommonTabButton,
    CommonCharacterIconButton,
    CommonItemIconButton,
    CommonIconDeselectButton,
    CommonSelectionButton,
    CommonFooterMyPageButton = 1101,
    CommonFooterCharacterButton,
    CommonFooterItemBoxButton,
    CommonFooterBattleButton,
    CommonFooterCompetitionButton,
    CommonFooterGachaButton,
    CommonFooterChatButton,
    CommonFooterGuildButton,
    CommonAcquisitionItem = 1201,
    CommonCharacterRankUpResult,
    CommonRankingReward,
    BattleBossBattleButton = 2001,
    BattleChallengeBattleButton,
    BattleResultWin,
    BattleResultLose,
    BattleQuickButton,
    BattleReward,
    BattleEffectStart = 2101,
    BattleEffectSkill,
    BattleEffectPhysicalDamage,
    BattleEffectMagicalDamage,
    BattleEffectBuff,
    BattleEffectDeBuff,
    BattleEffectRecover,
    BattleEffectMiss,
    BattleEffectPhysicalCriticalDamage,
    BattleEffectMagicalCriticalDamage,
    BattleEffectFloatingItem,
    BattleMapNewQuestMove = 2201,
    BattleMapChangeBuilding,
    BattleMapPopulationCount,
    BattleMapBuildingRemoveCurse,
    BattleMapChangeTerritory,
    BattleMapChangeWorld,
    CharacterSetLevelLink = 3001,
    CharacterReinforcement,
    CharacterSetParty,
    CharacterLevelUp,
    CharacterEquipmentStrengthening = 3006,
    CharacterEquipmentRefine,
    CharacterUnequip,
    CompetitionDungeonBattleButton = 4001,
    CompetitionTowerBattleButton,
    CompetitionGlobalPvpButton,
    CompetitionBountyQuestButton,
    CompetitionLocalPvpButton,
    CompetitionLocalRaidButton,
    DungeonBattleTileButton = 5001,
    DungeonBattleShowSelectRelic,
    DungeonBattleSelectGrid,
    DungeonBattleMoveGrid,
    DungeonBattleRevival,
    DungeonBattleChangeLayer,
    DungeonBattleSelectRelicButton,
    DungeonBattlePurchaseShopItemButton,
    DungeonBattleFloatingReward,
    DungeonBattleClear,
    TowerBattleUpStair = 6001,
    GachaDrawButton = 7001,
    GachaCharacterDraw = 7003,
    GachaNewCharacterDraw,
    GachaBonus,
    GachaEquipmentDraw = 7007,
    ChatSendButton = 8001,
    GvgKO = 9001,
    LevelLinkOpenPartyModeIconFlash = 10002,
    LevelLinkSubLevelStrengthen,
    LevelLinkBaseCharacterSet,
    ReleaseLock = 11001,
    StrengthenLightUp = 12001,
    Purchase = 13001,
    PanelMissionOpenGrid = 14001,
    PanelMissionBingo,
    PanelMissionFlashScreen,
    GuildTowerDifficultyUp = 16001,
    GvGKOWithEffect = 17001,
    GvgYesterdayMvp = 18001,
    BookSortUnlockGridCellSingle = 20001,
    BookSortUnlockGridCellBig,
    BookSortPopUpTreasureBox,
    BookSortMoveUnlockGridItem
}