namespace MementoMori.Ortega.Common.Enums
{
	public enum TransitionState
	{
		None,
		TitleDownloadAll,
		TitleSplash,
		MyPagePlayTouchAction,
		MyPagePictureBook,
		MyPageMission,
		MyPagePlayerInfo,
		MyPageMenu,
		MyPageCommunity,
		MyPageDeepLink,
		MyPageGuildRecruitTutorial,
		AutoBattleQuestInfo,
		AutoBattleQuestChangeWithNext,
		AutoBattleQuestChangeWithTap,
		AutoBattleQuestInfoFormation,
		AutoBattleReport,
		AutoBattleQuickMoveView,
		BattleSimulationReplay,
		CharacterListRankUp,
		ScenarioGameMode,
		ScenarioEditorMode,
		ScenarioDebugMode,
		TowerBattleFormation,
		DungeonBattleClear,
		DungeonBattleOpenFormation,
		GvgCastleInfo,
		GvgBattle,
		GvgMvp,
		LocalRaidReport,
		GuildTowerReinforcement
	}
}
