namespace MementoMori.Ortega.Common.Enums;

public enum TransitionState
{
    None,
    TitleDownloadAll,
    TitleSplash,
    MyPagePlayTouchAction,
    MyPagePictureBook,
    MyPageMission,
    MyPagePlayerInfo,
    MyPageMenu,
    MyPageCommunity,
    MyPageDeepLink,
    MyPageGuildRecruitTutorial,
    MyPageWeeklyTopics,
    MyPageEventPortal,
    AutoBattleQuestChangeWithNext,
    AutoBattleQuestChangeWithTap,
    AutoBattleQuestInfoFormation,
    AutoBattleReport,
    BattleSimulationReplay,
    CharacterListRankUp,
    ScenarioGameMode,
    ScenarioEditorMode,
    ScenarioDebugMode,
    TowerBattleFormation,
    DungeonBattleClear,
    DungeonBattleOpenFormation,
    GvgCastleInfo,
    GvgBattle,
    GvgMvp,
    LocalRaidReport,
    GuildTowerReinforcement
}