namespace MementoMori.Ortega.Common.Enums
{
	public enum TutorialButtonType
	{
		None,
		Ok,
		Close,
		Background,
		Content1 = 100,
		Content2,
		Content3,
		Content4,
		Content5,
		FooterCharacter = 200,
		FooterBattle,
		FooterGacha,
		FooterMyPage,
		FooterItemBox,
		FooterCompetition,
		FooterChat,
		FooterGuild,
		LevelUp = 300,
		Equipment,
		PictureBook,
		Memory,
		Formation,
		BattleReward,
		SphereSet,
		SphereSlot,
		BattleLoseCharacter,
		Exchange,
		CharacterMaxRarity,
		BattleLoseEquipment,
		EquipmentStrength,
		EquipmentRefine,
		EquipmentAscend,
		RankUpTab,
		RankUpBaseCharacter,
		RankUpMaterialCharacter1,
		RankUpMaterialCharacter2,
		RankUp,
		EquipmentRefineHighlight,
		MoveWorld,
		EquipmentAscendLevelSelect,
		LevelLink = 350,
		LevelLinkSlot1,
		NextChapter = 400,
		Mission = 500,
		MissionAllReceive,
		HeaderShop = 600,
		HeaderReturn,
		CompetitionLocalPvp = 700,
		CompetitionGlobalPvp,
		CompetitionLocalRaid,
		CompetitionTowerBattle,
		CompetitionDungeonBattle,
		CompetitionBountyQuest,
		Character1 = 1001,
		Character2,
		Character3,
		Character23 = 1023,
		GuildRecruitList = 1100,
		GuildRecruitWaitSetting,
		EquipmentSynchro = 1200,
		EquipmentSynchroMission,
		EquipmentSynchroUnlockGroup
	}
}
