namespace MementoMori.Ortega.Common.Enums
{
	public enum TutorialEventType
	{
		None,
		Guide,
		Story,
		NewCharacter,
		Movie,
		ReleaseFooter,
		TutorialDescriptionDialog,
		EditPlayerName,
		Building,
		RequestReward,
		DeckSetting,
		AssetDownload,
		LocalRaidDeck,
		ReleaseShopAndMission,
		CharacterLevelUpArrow,
		ReleaseCompetition,
		NewQuest,
		AppsFlyerEventTutorialCompletion,
		ShowBossBattleButtonArrow,
		ReleaseMyPage,
		PreLoadMapObject,
		MoveWorld,
		ReleaseEquipmentSynchro,
		EquipmentSynchroUnlockGroup
	}
}
