namespace MementoMori.Ortega.Common.Enums
{
	public enum VipPrivilegeType
	{
		ReachReward,
		AutoBattlePlayerExpBonus,
		DungeonBattleCoinBonus,
		DungeonBattleGoldBonus,
		QuickBattlePlayerExpBonus,
		DungeonBattleMissedCompensationCount,
		LoginBonusMissedCompensationCount,
		MaxBossAndTowerBattleUseCurrencyCount,
		MaxCharacterBoxPlus,
		MaxGuildRaidChallengeCount,
		MaxQuickUseCurrencyCount,
		MaxShopItemCountPlus,
		MaxSoloQuestCount,
		MaxTeamQuestCount,
		DestinyGachaAvailable,
		DestinyGachaLogAvailable,
		StarsGuidanceGachaAvailable,
		StarsGuidanceLogAvailable,
		StarsGuidanceTradeAvailable,
		LockEquipmentTrainingAvailable,
		MultipleBountyQuestAvailable,
		QuickBossAndTowerBattleAvailable,
		QuickStartGuildRaidAvailable,
		RefundEquipmentMergeAvailable,
		MultipleQuickStartGuildRaidAvailable
	}
}
