using System.ComponentModel;

namespace MementoMori.Ortega.Share.Enums
{
	[Description("ミッションタイプ")]
	public enum MissionType
	{
		Main,
		Daily,
		Weekly,
		BeginnerFirstDay = 311,
		BeginnerFirstDayLevel,
		BeginnerFirstDayStage,
		BeginnerFirstDayBuy,
		BeginnerSecondDay = 321,
		BeginnerSecondDayQuick,
		BeginnerSecondDayBattleLeague,
		BeginnerSecondDayBuy,
		BeginnerThirdDay = 331,
		BeginnerThirdDayForge,
		BeginnerThirdDayDungeonBattle,
		BeginnerThirdDayBuy,
		BeginnerFourthDay = 341,
		BeginnerFourthDayReinforceEquipment,
		BeginnerFourthDayTowerBattle,
		BeginnerFourthDayBuy,
		BeginnerFifthDay = 351,
		BeginnerFifthDayBountyQuest,
		BeginnerFifthDayTotalCharacter,
		BeginnerFifthDayBuy,
		BeginnerSixthDay = 361,
		BeginnerSixthDaySphere,
		BeginnerSixthDayCharacterEvolution,
		BeginnerSixthDayBuy,
		BeginnerSeventhDay = 371,
		BeginnerSeventhDayTraining,
		BeginnerSeventhDayLocalRaid,
		BeginnerSeventhDayBuy,
		ComebackLogin = 401,
		ComebackActivity,
		ComebackConsumeCurrency,
		NewCharacter = 5,
		LimitedFirstDayTab1 = 611,
		LimitedFirstDayTab2,
		LimitedFirstDayTab3,
		LimitedFirstDayTab4,
		LimitedSecondDayTab1 = 621,
		LimitedSecondDayTab2,
		LimitedSecondDayTab3,
		LimitedSecondDayTab4,
		LimitedThirdDayTab1 = 631,
		LimitedThirdDayTab2,
		LimitedThirdDayTab3,
		LimitedThirdDayTab4,
		LimitedFourthDayTab1 = 641,
		LimitedFourthDayTab2,
		LimitedFourthDayTab3,
		LimitedFourthDayTab4,
		LimitedFifthDayTab1 = 651,
		LimitedFifthDayTab2,
		LimitedFifthDayTab3,
		LimitedFifthDayTab4,
		LimitedSixthDayTab1 = 661,
		LimitedSixthDayTab2,
		LimitedSixthDayTab3,
		LimitedSixthDayTab4,
		LimitedSeventhDayTab1 = 671,
		LimitedSeventhDayTab2,
		LimitedSeventhDayTab3,
		LimitedSeventhDayTab4,
		PanelSheet1 = 901,
		PanelSheet2,
		PanelSheet3,
		Guild = 10,
		GuildTower,
		Collab,
		PopularityVote,
		BookSort,
		RentalRaid
	}
}
