using System.ComponentModel;

namespace MementoMori.Ortega.Share.Enums.Battle.Skill
{
	[Description("攻撃サブオプション種別")]
	public enum AttackOptionSubType
	{
		[Description("常にTrue")]
		None,
		[Description("相手HP割合がValue以上")]
		OverTargetHpPercent,
		[Description("相手HP割合がValue未満")]
		UnderTargetHpPercent,
		[Description("自分HP割合がValue以上")]
		OverSelfHpPercent,
		[Description("自分HP割合がValue未満")]
		UnderSelfHpPercent,
		[Description("相手HP割合が自分HP割合の比率以上")]
		OverTargetHpPercentThanMe,
		[Description("相手HP割合が自分HP割合の比率未満")]
		UnderTargetHpPercentThanMe,
		[Description("相手攻撃力が自分攻撃力の比率以上")]
		OverTargetAttackPowerThanMe,
		[Description("相手攻撃力が自分攻撃力の比率未満")]
		UnderTargetAttackPowerThanMe,
		[Description("相手腕力が自分腕力の比率以上")]
		OverTargetMuscleThanMe,
		[Description("相手腕力が自分腕力の比率未満")]
		UnderTargetMuscleThanMe,
		[Description("相手技力が自分技力の比率以上")]
		OverTargetEnergyThanMe,
		[Description("相手技力が自分技力の比率未満")]
		UnderTargetEnergyThanMe,
		[Description("相手魔力が自分魔力の比率以上")]
		OverTargetIntelligenceThanMe,
		[Description("相手魔力が自分魔力の比率未満")]
		UnderTargetIntelligenceThanMe,
		[Description("指定EffectType所持数が1以上")]
		AnyCountTargetEffectType,
		[Description("指定EffectType所持数が0")]
		ZeroCountTargetEffectType,
		[Description("指定EffectGroupId所持数が1以上")]
		AnyCountTargetEffectGroupId,
		[Description("指定EffectGroupId所持数が0")]
		ZeroCountTargetEffectGroupId,
		[Description("バフ所有数が指定値以上")]
		OverTargetBuffCount,
		[Description("バフ所有数が指定値未満")]
		UnderTargetBuffCount,
		[Description("デバフ所有数が指定値以上")]
		OverTargetDeBuffCount,
		[Description("デバフ所有数が指定値未満")]
		UnderTargetDeBuffCount,
		[Description("命中回数が指定値以上")]
		OverSelfHitCount,
		[Description("クリティカル回数が指定値以上")]
		OverSelfCriticalCount,
		[Description("自分の指定EffectType所持数が1以上")]
		AnyCountSelfEffectType,
		[Description("自分の指定EffectType所持数が0 ")]
		ZeroCountSelfEffectType,
		[Description("自分の指定EffectGroupId所持数が1以上")]
		AnyCountSelfEffectGroupId,
		[Description("自分の指定EffectGroupId所持数が0")]
		ZeroCountSelfEffectGroupId,
		[Description("自分のバフ所有数が指定値以上")]
		OverSelfBuffCount,
		[Description("自分のバフ所有数が指定値未満")]
		UnderSelfBuffCount,
		[Description("自分のデバフ所有数が指定値以上")]
		OverSelfDeBuffCount,
		[Description("自分のデバフ所有数が指定値未満")]
		UnderSelfDeBuffCount,
        [Description("相手のJobFlagsが指定値")]
        TargetJobFlags,
        [Description("相手のElementTypeが指定値")]
        TargetElementType
	}
}
