//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MementoMori.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MementoMori.Common.Localization.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error count reached {0} times, abort 的本地化字符串。
        /// </summary>
        public static string AutoBossErrorMessage {
            get {
                return ResourceManager.GetString("AutoBossErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challage {0} boss one time：{1},  total：{2}, Success：{3}, Err: {4} 的本地化字符串。
        /// </summary>
        public static string AutoBossExecMessage {
            get {
                return ResourceManager.GetString("AutoBossExecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Gacha 的本地化字符串。
        /// </summary>
        public static string AutoGacha {
            get {
                return ResourceManager.GetString("AutoGacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Gacha Consume Items 的本地化字符串。
        /// </summary>
        public static string AutoGachaConsumeItems {
            get {
                return ResourceManager.GetString("AutoGachaConsumeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Job Crons 的本地化字符串。
        /// </summary>
        public static string AutoJobCrons {
            get {
                return ResourceManager.GetString("AutoJobCrons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Job Switchs 的本地化字符串。
        /// </summary>
        public static string AutoJobSwitchs {
            get {
                return ResourceManager.GetString("AutoJobSwitchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Legend Inheritance To D Rarity 的本地化字符串。
        /// </summary>
        public static string AutoLegendInheritance {
            get {
                return ResourceManager.GetString("AutoLegendInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Matchless Inheritance To D Rarity 的本地化字符串。
        /// </summary>
        public static string AutoMatchlessInheritance {
            get {
                return ResourceManager.GetString("AutoMatchlessInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Request Delay 的本地化字符串。
        /// </summary>
        public static string AutoRequestDelay {
            get {
                return ResourceManager.GetString("AutoRequestDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challage {0} {1} layer one time：{2},  {6}/10,total：{3}, Success：{4}, Err: {5} 的本地化字符串。
        /// </summary>
        public static string AutoTowerElementExecMsg {
            get {
                return ResourceManager.GetString("AutoTowerElementExecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Challage {0} {1} layer one time：{2},  total：{3}, Success：{4}, Err: {5} 的本地化字符串。
        /// </summary>
        public static string AutoTowerInfiniteExecMsg {
            get {
                return ResourceManager.GetString("AutoTowerInfiniteExecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battle Result 的本地化字符串。
        /// </summary>
        public static string BattleResult {
            get {
                return ResourceManager.GetString("BattleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically dispatch tasks when the following rewards are available 的本地化字符串。
        /// </summary>
        public static string BountyQuestTargetItems {
            get {
                return ResourceManager.GetString("BountyQuestTargetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buy {0}×{1} Success 的本地化字符串。
        /// </summary>
        public static string CaveBuyItemSuccess {
            get {
                return ResourceManager.GetString("CaveBuyItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current at {0} layer，coordinate {1},{2}，state {3}, {4}, enemy battle power {5} 的本地化字符串。
        /// </summary>
        public static string CaveCurrentState {
            get {
                return ResourceManager.GetString("CaveCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Next 的本地化字符串。
        /// </summary>
        public static string CaveErrorRelicExist {
            get {
                return ResourceManager.GetString("CaveErrorRelicExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error when select support member, {0}, continue to next one 的本地化字符串。
        /// </summary>
        public static string CaveErrorSelectSupport {
            get {
                return ResourceManager.GetString("CaveErrorSelectSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Info 的本地化字符串。
        /// </summary>
        public static string CharacterInfo {
            get {
                return ResourceManager.GetString("CharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron Expression 的本地化字符串。
        /// </summary>
        public static string CronExpression {
            get {
                return ResourceManager.GetString("CronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily Job  的本地化字符串。
        /// </summary>
        public static string DailyJob {
            get {
                return ResourceManager.GetString("DailyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily Job Cron Expression 的本地化字符串。
        /// </summary>
        public static string DailyJobCronExpression {
            get {
                return ResourceManager.GetString("DailyJobCronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Designated the target prop 的本地化字符串。
        /// </summary>
        public static string DesignatedTargetProp {
            get {
                return ResourceManager.GetString("DesignatedTargetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable All Jobs 的本地化字符串。
        /// </summary>
        public static string DisableAllJobs {
            get {
                return ResourceManager.GetString("DisableAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discount Percentage for Products 的本地化字符串。
        /// </summary>
        public static string DiscountPercentageforProducts {
            get {
                return ResourceManager.GetString("DiscountPercentageforProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispatched 的本地化字符串。
        /// </summary>
        public static string Dispatched {
            get {
                return ResourceManager.GetString("Dispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not specified target prop or forced dispatch, dispatching all tasks. 的本地化字符串。
        /// </summary>
        public static string DispatchingAll {
            get {
                return ResourceManager.GetString("DispatchingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispatching the target prop mission 的本地化字符串。
        /// </summary>
        public static string DispatchingTargetPropMission {
            get {
                return ResourceManager.GetString("DispatchingTargetPropMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items to be automatically purchased from the shop 的本地化字符串。
        /// </summary>
        public static string DungeonBattleTargetItems {
            get {
                return ResourceManager.GetString("DungeonBattleTargetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter 的本地化字符串。
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute All Actions 的本地化字符串。
        /// </summary>
        public static string ExecuteAllQuick {
            get {
                return ResourceManager.GetString("ExecuteAllQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Output 的本地化字符串。
        /// </summary>
        public static string ExecutionOutput {
            get {
                return ResourceManager.GetString("ExecutionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For equipment, find a wearable character, and then unequip once. 的本地化字符串。
        /// </summary>
        public static string FindEquipmentCharacter {
            get {
                return ResourceManager.GetString("FindEquipmentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Dispatch 的本地化字符串。
        /// </summary>
        public static string ForceDispatch {
            get {
                return ResourceManager.GetString("ForceDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gacha {0} {1} times, used {2}×{3} 的本地化字符串。
        /// </summary>
        public static string GachaExecInfo {
            get {
                return ResourceManager.GetString("GachaExecInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gacha Result 的本地化字符串。
        /// </summary>
        public static string GachaResult {
            get {
                return ResourceManager.GetString("GachaResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Assistant 的本地化字符串。
        /// </summary>
        public static string GameAssistant {
            get {
                return ResourceManager.GetString("GameAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count Limit 的本地化字符串。
        /// </summary>
        public static string ItemLimitCount {
            get {
                return ResourceManager.GetString("ItemLimitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum use quantity for recovery items (0 means not using) 的本地化字符串。
        /// </summary>
        public static string MaxUseRecoveryItem {
            get {
                return ResourceManager.GetString("MaxUseRecoveryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Execution Time 的本地化字符串。
        /// </summary>
        public static string NextExecutionTime {
            get {
                return ResourceManager.GetString("NextExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Available {0} 的本地化字符串。
        /// </summary>
        public static string NoAvailable {
            get {
                return ResourceManager.GetString("NoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Available Gacha 的本地化字符串。
        /// </summary>
        public static string NoAvailableGacha {
            get {
                return ResourceManager.GetString("NoAvailableGacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Inheritable D Rarity Equipments 的本地化字符串。
        /// </summary>
        public static string NoInheritableDRarityEquip {
            get {
                return ResourceManager.GetString("NoInheritableDRarityEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Legend Equipments 的本地化字符串。
        /// </summary>
        public static string NoLegendEquip {
            get {
                return ResourceManager.GetString("NoLegendEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing to receive 的本地化字符串。
        /// </summary>
        public static string NothingToReceive {
            get {
                return ResourceManager.GetString("NothingToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no more items to smelt. 的本地化字符串。
        /// </summary>
        public static string NothingToSmelt {
            get {
                return ResourceManager.GetString("NothingToSmelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Received 的本地化字符串。
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Selected 的本地化字符串。
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Started 的本地化字符串。
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Unlocked 的本地化字符串。
        /// </summary>
        public static string NotUnlocked {
            get {
                return ResourceManager.GetString("NotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ongoing 的本地化字符串。
        /// </summary>
        public static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Click Login to Use Assistant 的本地化字符串。
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritize selecting treasure chest nodes 的本地化字符串。
        /// </summary>
        public static string PreferTreasureChest {
            get {
                return ResourceManager.GetString("PreferTreasureChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put on all equips of {0} {1} 的本地化字符串。
        /// </summary>
        public static string PutOnEquipmentOfCharacter {
            get {
                return ResourceManager.GetString("PutOnEquipmentOfCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Actions 的本地化字符串。
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reinforce Equipment Once 的本地化字符串。
        /// </summary>
        public static string ReinforceEquipmentOnce {
            get {
                return ResourceManager.GetString("ReinforceEquipmentOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove all equips of {0} {1} 的本地化字符串。
        /// </summary>
        public static string RemoveEquipmentOfCharacter {
            get {
                return ResourceManager.GetString("RemoveEquipmentOfCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward Claim Job 的本地化字符串。
        /// </summary>
        public static string RewardClaimJob {
            get {
                return ResourceManager.GetString("RewardClaimJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward Claim Job Cron Expression 的本地化字符串。
        /// </summary>
        public static string RewardClaimJobCronExpression {
            get {
                return ResourceManager.GetString("RewardClaimJobCronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get {0} &apos;s {1} Reward 的本地化字符串。
        /// </summary>
        public static string RewardMissionMsg {
            get {
                return ResourceManager.GetString("RewardMissionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reward Medal 的本地化字符串。
        /// </summary>
        public static string RewardMissonActivity {
            get {
                return ResourceManager.GetString("RewardMissonActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected {0} Items 的本地化字符串。
        /// </summary>
        public static string SelectedXItems {
            get {
                return ResourceManager.GetString("SelectedXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Player 的本地化字符串。
        /// </summary>
        public static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync 的本地化字符串。
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync User Info 的本地化字符串。
        /// </summary>
        public static string SyncUserInfo {
            get {
                return ResourceManager.GetString("SyncUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Value 的本地化字符串。
        /// </summary>
        public static string TargetValue {
            get {
                return ResourceManager.GetString("TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tower Type 的本地化字符串。
        /// </summary>
        public static string TowerType {
            get {
                return ResourceManager.GetString("TowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unkonow 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Normal Items 的本地化字符串。
        /// </summary>
        public static string UseNormalItems {
            get {
                return ResourceManager.GetString("UseNormalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use over limit item 的本地化字符串。
        /// </summary>
        public static string UseOverLimitItem {
            get {
                return ResourceManager.GetString("UseOverLimitItem", resourceCulture);
            }
        }
    }
}
