//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MementoMori.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MementoMori.Common.Localization.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Creation Time.
        /// </summary>
        public static string Account_Creation_Time {
            get {
                return ResourceManager.GetString("Account Creation Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount consumed.
        /// </summary>
        public static string Amount_consumed {
            get {
                return ResourceManager.GetString("Amount consumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any amount.
        /// </summary>
        public static string Any_amount {
            get {
                return ResourceManager.GetString("Any amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Items.
        /// </summary>
        public static string AnyItems {
            get {
                return ResourceManager.GetString("AnyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto accept friend requests.
        /// </summary>
        public static string Auto_accept_friend_requests {
            get {
                return ResourceManager.GetString("Auto accept friend requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto challenge retry count.
        /// </summary>
        public static string Auto_challenge_retry_count {
            get {
                return ResourceManager.GetString("Auto challenge retry count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto draw 10 times (up to 3 draws).
        /// </summary>
        public static string Auto_draw_10_times__up_to_3_draws_ {
            get {
                return ResourceManager.GetString("Auto draw 10 times (up to 3 draws)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-refresh diamonds.
        /// </summary>
        public static string Auto_refresh_diamonds {
            get {
                return ResourceManager.GetString("Auto refresh diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto remove whitelist.
        /// </summary>
        public static string Auto_remove_whitelist {
            get {
                return ResourceManager.GetString("Auto remove whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto send friend requests.
        /// </summary>
        public static string Auto_send_friend_requests {
            get {
                return ResourceManager.GetString("Auto send friend requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto unequip gear during events.
        /// </summary>
        public static string Auto_unequip_gear_during_events {
            get {
                return ResourceManager.GetString("Auto unequip gear during events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error count reached {0} times, abort.
        /// </summary>
        public static string AutoBossErrorMessage {
            get {
                return ResourceManager.GetString("AutoBossErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge {0} boss one time：{1},  total：{2}, Success：{3}, Err: {4}.
        /// </summary>
        public static string AutoBossExecMessage {
            get {
                return ResourceManager.GetString("AutoBossExecMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Purchase.
        /// </summary>
        public static string AutoBuy {
            get {
                return ResourceManager.GetString("AutoBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Gacha.
        /// </summary>
        public static string AutoGacha {
            get {
                return ResourceManager.GetString("AutoGacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Gacha Consume Items.
        /// </summary>
        public static string AutoGachaConsumeItems {
            get {
                return ResourceManager.GetString("AutoGachaConsumeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Job Crons.
        /// </summary>
        public static string AutoJobCrons {
            get {
                return ResourceManager.GetString("AutoJobCrons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Job Switchs.
        /// </summary>
        public static string AutoJobSwitchs {
            get {
                return ResourceManager.GetString("AutoJobSwitchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Legend Inheritance To D Rarity.
        /// </summary>
        public static string AutoLegendInheritance {
            get {
                return ResourceManager.GetString("AutoLegendInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        public static string AutoLogin {
            get {
                return ResourceManager.GetString("AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login on Startup.
        /// </summary>
        public static string AutoLoginonStartup {
            get {
                return ResourceManager.GetString("AutoLoginonStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Matchless Inheritance To D Rarity.
        /// </summary>
        public static string AutoMatchlessInheritance {
            get {
                return ResourceManager.GetString("AutoMatchlessInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically select this world when auto logging in.
        /// </summary>
        public static string Automatically_select_this_world_when_auto_logging_in {
            get {
                return ResourceManager.GetString("Automatically select this world when auto logging in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Request Delay.
        /// </summary>
        public static string AutoRequestDelay {
            get {
                return ResourceManager.GetString("AutoRequestDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge {0} {1} layer one time：{2},  {6}/10,total：{3}, Success：{4}, Err: {5}.
        /// </summary>
        public static string AutoTowerElementExecMsg {
            get {
                return ResourceManager.GetString("AutoTowerElementExecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge {0} {1} layer one time：{2},  total：{3}, Success：{4}, Err: {5}.
        /// </summary>
        public static string AutoTowerInfiniteExecMsg {
            get {
                return ResourceManager.GetString("AutoTowerInfiniteExecMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amphora.
        /// </summary>
        public static string AutoUseItemTypeAmphora {
            get {
                return ResourceManager.GetString("AutoUseItemTypeAmphora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest of Chance.
        /// </summary>
        public static string AutoUseItemTypeChestOfChance {
            get {
                return ResourceManager.GetString("AutoUseItemTypeChestOfChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Bag.
        /// </summary>
        public static string AutoUseItemTypeDiamondBag {
            get {
                return ResourceManager.GetString("AutoUseItemTypeDiamondBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Rune.
        /// </summary>
        public static string AutoUseItemTypeMysteryRune {
            get {
                return ResourceManager.GetString("AutoUseItemTypeMysteryRune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string AutoUseItemTypeOthers {
            get {
                return ResourceManager.GetString("AutoUseItemTypeOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pot.
        /// </summary>
        public static string AutoUseItemTypePot {
            get {
                return ResourceManager.GetString("AutoUseItemTypePot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sealed Chest.
        /// </summary>
        public static string AutoUseItemTypeSealedChest {
            get {
                return ResourceManager.GetString("AutoUseItemTypeSealedChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch&apos;s Letter Gift.
        /// </summary>
        public static string AutoUseItemTypeWitchLetterGift {
            get {
                return ResourceManager.GetString("AutoUseItemTypeWitchLetterGift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch&apos;s Letter(R).
        /// </summary>
        public static string AutoUseItemTypeWitchLetterR {
            get {
                return ResourceManager.GetString("AutoUseItemTypeWitchLetterR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch&apos;s Letter(SR).
        /// </summary>
        public static string AutoUseItemTypeWitchLetterSr {
            get {
                return ResourceManager.GetString("AutoUseItemTypeWitchLetterSr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch&apos;s Shard.
        /// </summary>
        public static string AutoUseItemTypeWitchShard {
            get {
                return ResourceManager.GetString("AutoUseItemTypeWitchShard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaned {0} log files.
        /// </summary>
        public static string BattleLogCleanComplete {
            get {
                return ResourceManager.GetString("BattleLogCleanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to clean {0} log files (total {1})?.
        /// </summary>
        public static string BattleLogCleanConfirm {
            get {
                return ResourceManager.GetString("BattleLogCleanConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file {0}: {1}.
        /// </summary>
        public static string BattleLogCleanError {
            get {
                return ResourceManager.GetString("BattleLogCleanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day ago.
        /// </summary>
        public static string BattleLogCleanOption1Day {
            get {
                return ResourceManager.GetString("BattleLogCleanOption1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 month ago.
        /// </summary>
        public static string BattleLogCleanOption1Month {
            get {
                return ResourceManager.GetString("BattleLogCleanOption1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week ago.
        /// </summary>
        public static string BattleLogCleanOption1Week {
            get {
                return ResourceManager.GetString("BattleLogCleanOption1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string BattleLogCleanOptionAll {
            get {
                return ResourceManager.GetString("BattleLogCleanOptionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Range.
        /// </summary>
        public static string BattleLogCleanRange {
            get {
                return ResourceManager.GetString("BattleLogCleanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log files to clean.
        /// </summary>
        public static string BattleLogNoFilesToClean {
            get {
                return ResourceManager.GetString("BattleLogNoFilesToClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Result.
        /// </summary>
        public static string BattleResult {
            get {
                return ResourceManager.GetString("BattleResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically dispatch tasks when the following rewards are available.
        /// </summary>
        public static string BountyQuestTargetItems {
            get {
                return ResourceManager.GetString("BountyQuestTargetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {1} with {0}.
        /// </summary>
        public static string BuyWith {
            get {
                return ResourceManager.GetString("BuyWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy {0}×{1} Success.
        /// </summary>
        public static string CaveBuyItemSuccess {
            get {
                return ResourceManager.GetString("CaveBuyItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current at {0} layer，coordinate {1},{2}，state {3}, {4}, enemy battle power {5}.
        /// </summary>
        public static string CaveCurrentState {
            get {
                return ResourceManager.GetString("CaveCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Next.
        /// </summary>
        public static string CaveErrorRelicExist {
            get {
                return ResourceManager.GetString("CaveErrorRelicExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when select support member, {0}, continue to next one.
        /// </summary>
        public static string CaveErrorSelectSupport {
            get {
                return ResourceManager.GetString("CaveErrorSelectSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Filter.
        /// </summary>
        public static string Character_Filter {
            get {
                return ResourceManager.GetString("Character Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Info.
        /// </summary>
        public static string CharacterInfo {
            get {
                return ResourceManager.GetString("CharacterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm removal of this account?.
        /// </summary>
        public static string Confirm_removal_of_this_account_ {
            get {
                return ResourceManager.GetString("Confirm removal of this account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumed Items.
        /// </summary>
        public static string ConsumeItem {
            get {
                return ResourceManager.GetString("ConsumeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron Expression.
        /// </summary>
        public static string CronExpression {
            get {
                return ResourceManager.GetString("CronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current expected value: {0}. Today, {1}/{2} auto-refreshes completed. Refreshing now..
        /// </summary>
        public static string Current_expected_value___0___Today___1___2__auto_refreshes_completed__Refreshing_now_ {
            get {
                return ResourceManager.GetString("Current expected value: {0}. Today, {1}/{2} auto-refreshes completed. Refreshing " +
                        "now.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Job.
        /// </summary>
        public static string DailyJob {
            get {
                return ResourceManager.GetString("DailyJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Job Cron Expression.
        /// </summary>
        public static string DailyJobCronExpression {
            get {
                return ResourceManager.GetString("DailyJobCronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy defense.
        /// </summary>
        public static string Deploy_defense {
            get {
                return ResourceManager.GetString("Deploy defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designated the target prop.
        /// </summary>
        public static string DesignatedTargetProp {
            get {
                return ResourceManager.GetString("DesignatedTargetProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All Jobs.
        /// </summary>
        public static string DisableAllJobs {
            get {
                return ResourceManager.GetString("DisableAllJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage for Products.
        /// </summary>
        public static string DiscountPercentageforProducts {
            get {
                return ResourceManager.GetString("DiscountPercentageforProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatched.
        /// </summary>
        public static string Dispatched {
            get {
                return ResourceManager.GetString("Dispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified target prop or forced dispatch, dispatching all tasks.
        /// </summary>
        public static string DispatchingAll {
            get {
                return ResourceManager.GetString("DispatchingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatching the target prop mission.
        /// </summary>
        public static string DispatchingTargetPropMission {
            get {
                return ResourceManager.GetString("DispatchingTargetPropMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download master directory completed.
        /// </summary>
        public static string Download_master_directory_completed {
            get {
                return ResourceManager.GetString("Download master directory completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading master directory....
        /// </summary>
        public static string Downloading_master_directory___ {
            get {
                return ResourceManager.GetString("Downloading master directory...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to be automatically purchased from the shop.
        /// </summary>
        public static string DungeonBattleTargetItems {
            get {
                return ResourceManager.GetString("DungeonBattleTargetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 0 to disable auto-refresh. Each refresh costs 20 diamonds and only refreshes if the expected value is greater than 20. For a single task: level 8 has an expected value of 13, level 7 is 11.6, level 6 is 9.8, level 5 is 7.9, and level 4 is 5.7. Auto-refresh is disabled for levels below 4. Expected values automatically account for double reward events..
        /// </summary>
        public static string Enter_0_to_disable_auto_refresh_ {
            get {
                return ResourceManager.GetString("Enter 0 to disable auto-refresh.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude {0}.
        /// </summary>
        public static string Exclude__0_ {
            get {
                return ResourceManager.GetString("Exclude {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude {0} higher than {1}.
        /// </summary>
        public static string Exclude__battleParameterName__higher_than__characterName_ {
            get {
                return ResourceManager.GetString("Exclude {battleParameterName} higher than {characterName}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude character.
        /// </summary>
        public static string Exclude_character {
            get {
                return ResourceManager.GetString("Exclude character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude enemy character with higher stats in the same attribute as ours.
        /// </summary>
        public static string Exclude_enemy_character_with_higher_stats_in_the_same_attribute_as_ours {
            get {
                return ResourceManager.GetString("Exclude enemy character with higher stats in the same attribute as ours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude player IDs (comma-separated).
        /// </summary>
        public static string Exclude_player_IDs__comma_separated_ {
            get {
                return ResourceManager.GetString("Exclude player IDs (comma-separated)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute All Actions.
        /// </summary>
        public static string ExecuteAllQuick {
            get {
                return ResourceManager.GetString("ExecuteAllQuick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Output.
        /// </summary>
        public static string ExecutionOutput {
            get {
                return ResourceManager.GetString("ExecutionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve account information.
        /// </summary>
        public static string Failed_to_retrieve_account_information {
            get {
                return ResourceManager.GetString("Failed to retrieve account information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering strategy.
        /// </summary>
        public static string Filtering_strategy {
            get {
                return ResourceManager.GetString("Filtering strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For equipment, find a wearable character, and then unequip once.
        /// </summary>
        public static string FindEquipmentCharacter {
            get {
                return ResourceManager.GetString("FindEquipmentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Dispatch.
        /// </summary>
        public static string ForceDispatch {
            get {
                return ResourceManager.GetString("ForceDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gacha {0} {1} times, used {2}×{3}.
        /// </summary>
        public static string GachaExecInfo {
            get {
                return ResourceManager.GetString("GachaExecInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gacha Result.
        /// </summary>
        public static string GachaResult {
            get {
                return ResourceManager.GetString("GachaResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Assistant.
        /// </summary>
        public static string GameAssistant {
            get {
                return ResourceManager.GetString("GameAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Limit.
        /// </summary>
        public static string ItemLimitCount {
            get {
                return ResourceManager.GetString("ItemLimitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login expired, please log in again.
        /// </summary>
        public static string Login_expired__please_log_in_again {
            get {
                return ResourceManager.GetString("Login expired, please log in again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed, please check your account configuration.
        /// </summary>
        public static string Login_failed__please_check_your_account_configuration {
            get {
                return ResourceManager.GetString("Login failed, please check your account configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        public static string Login_successful {
            get {
                return ResourceManager.GetString("Login successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successful.
        /// </summary>
        public static string Logout_successful {
            get {
                return ResourceManager.GetString("Logout successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Account.
        /// </summary>
        public static string MainAccount {
            get {
                return ResourceManager.GetString("MainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Battle Power.
        /// </summary>
        public static string Max_Battle_Power {
            get {
                return ResourceManager.GetString("Max Battle Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max refresh count.
        /// </summary>
        public static string Max_refresh_count {
            get {
                return ResourceManager.GetString("Max refresh count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum use quantity for recovery items (0 means not using).
        /// </summary>
        public static string MaxUseRecoveryItem {
            get {
                return ResourceManager.GetString("MaxUseRecoveryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Battle Power.
        /// </summary>
        public static string Min_Battle_Power {
            get {
                return ResourceManager.GetString("Min Battle Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Execution Time.
        /// </summary>
        public static string NextExecutionTime {
            get {
                return ResourceManager.GetString("NextExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available support characters found..
        /// </summary>
        public static string No_available_support_characters_found_ {
            get {
                return ResourceManager.GetString("No available support characters found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployable castles available.
        /// </summary>
        public static string No_deployable_castles_available {
            get {
                return ResourceManager.GetString("No deployable castles available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setting means buying any item.
        /// </summary>
        public static string No_setting_means_buying_any_item {
            get {
                return ResourceManager.GetString("No setting means buying any item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No setting means using any item for purchase.
        /// </summary>
        public static string No_setting_means_using_any_item_for_purchase {
            get {
                return ResourceManager.GetString("No setting means using any item for purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available {0}.
        /// </summary>
        public static string NoAvailable {
            get {
                return ResourceManager.GetString("NoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Gacha.
        /// </summary>
        public static string NoAvailableGacha {
            get {
                return ResourceManager.GetString("NoAvailableGacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inheritable D Rarity Equipments.
        /// </summary>
        public static string NoInheritableDRarityEquip {
            get {
                return ResourceManager.GetString("NoInheritableDRarityEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Legend Equipments.
        /// </summary>
        public static string NoLegendEquip {
            get {
                return ResourceManager.GetString("NoLegendEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stop.
        /// </summary>
        public static string NoStop {
            get {
                return ResourceManager.GetString("NoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to receive.
        /// </summary>
        public static string NothingToReceive {
            get {
                return ResourceManager.GetString("NothingToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no more items to smelt.
        /// </summary>
        public static string NothingToSmelt {
            get {
                return ResourceManager.GetString("NothingToSmelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Logged In.
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Received.
        /// </summary>
        public static string NotReceived {
            get {
                return ResourceManager.GetString("NotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Unlocked.
        /// </summary>
        public static string NotUnlocked {
            get {
                return ResourceManager.GetString("NotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string OnGoing {
            get {
                return ResourceManager.GetString("OnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent Selection Strategy.
        /// </summary>
        public static string Opponent_Selection_Strategy {
            get {
                return ResourceManager.GetString("Opponent Selection Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Click Login to Use Assistant.
        /// </summary>
        public static string PleaseLogin {
            get {
                return ResourceManager.GetString("PleaseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritize selecting treasure chest nodes.
        /// </summary>
        public static string PreferTreasureChest {
            get {
                return ResourceManager.GetString("PreferTreasureChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put on all equips of {0} {1}.
        /// </summary>
        public static string PutOnEquipmentOfCharacter {
            get {
                return ResourceManager.GetString("PutOnEquipmentOfCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh limit reached, dispatch directly.
        /// </summary>
        public static string Refresh_limit_reached__dispatch_directly {
            get {
                return ResourceManager.GetString("Refresh limit reached, dispatch directly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforce Equipment Once.
        /// </summary>
        public static string ReinforceEquipmentOnce {
            get {
                return ResourceManager.GetString("ReinforceEquipmentOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove friends inactive for 7 days.
        /// </summary>
        public static string Remove_friends_inactive_for_7_days {
            get {
                return ResourceManager.GetString("Remove friends inactive for 7 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all equips of {0} {1}.
        /// </summary>
        public static string RemoveEquipmentOfCharacter {
            get {
                return ResourceManager.GetString("RemoveEquipmentOfCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out, check your network..
        /// </summary>
        public static string Request_timed_out__check_your_network {
            get {
                return ResourceManager.GetString("Request timed out, check your network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string ResettoDefault {
            get {
                return ResourceManager.GetString("ResettoDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Claim Job.
        /// </summary>
        public static string RewardClaimJob {
            get {
                return ResourceManager.GetString("RewardClaimJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Claim Job Cron Expression.
        /// </summary>
        public static string RewardClaimJobCronExpression {
            get {
                return ResourceManager.GetString("RewardClaimJobCronExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get {0} &apos;s {1} Reward.
        /// </summary>
        public static string RewardMissionMsg {
            get {
                return ResourceManager.GetString("RewardMissionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Medal.
        /// </summary>
        public static string RewardMissonActivity {
            get {
                return ResourceManager.GetString("RewardMissonActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful.
        /// </summary>
        public static string Save_successful {
            get {
                return ResourceManager.GetString("Save successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds of pre-battle wait time.
        /// </summary>
        public static string Seconds_of_pre_battle_wait_time {
            get {
                return ResourceManager.GetString("Seconds of pre-battle wait time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tasks based on reward quantity and weight.
        /// </summary>
        public static string Select_tasks_based_on_reward_quantity_and_weight {
            get {
                return ResourceManager.GetString("Select tasks based on reward quantity and weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0} Items.
        /// </summary>
        public static string SelectedXItems {
            get {
                return ResourceManager.GetString("SelectedXItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Player.
        /// </summary>
        public static string SelectPlayer {
            get {
                return ResourceManager.GetString("SelectPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 for any amount.
        /// </summary>
        public static string Set_to_0_for_any_amount {
            get {
                return ResourceManager.GetString("Set to 0 for any amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Buy Store Items.
        /// </summary>
        public static string ShopAutoBuyItems {
            get {
                return ResourceManager.GetString("ShopAutoBuyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify at least one: Store Items or Consumables.
        /// </summary>
        public static string ShopAutoBuyPleaseSelectOne {
            get {
                return ResourceManager.GetString("ShopAutoBuyPleaseSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop after specified stage.
        /// </summary>
        public static string StopAfterSpecifiedStage {
            get {
                return ResourceManager.GetString("StopAfterSpecifiedStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deployed {1} in {0}.
        /// </summary>
        public static string Successfully_deployed {
            get {
                return ResourceManager.GetString("Successfully deployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Account.
        /// </summary>
        public static string SwitchAccount {
            get {
                return ResourceManager.GetString("SwitchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync User Info.
        /// </summary>
        public static string SyncUserInfo {
            get {
                return ResourceManager.GetString("SyncUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Value.
        /// </summary>
        public static string TargetValue {
            get {
                return ResourceManager.GetString("TargetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version ({0}) is not the latest version ({1}). Click to download the latest version..
        /// </summary>
        public static string The_current_version___0___is_not_the_latest_version___1____Click_to_download_the_latest_version_ {
            get {
                return ResourceManager.GetString("The current version ({0}) is not the latest version ({1}). Click to download the " +
                        "latest version.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected diamond value of the current task is now below 20, do not refresh, dispatch directly..
        /// </summary>
        public static string The_expected_diamond_value_of_the_current_task_is_now_below_20__do_not_refresh__dispatch_directly_ {
            get {
                return ResourceManager.GetString("The expected diamond value of the current task is now below 20, do not refresh, d" +
                        "ispatch directly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Type.
        /// </summary>
        public static string TowerType {
            get {
                return ResourceManager.GetString("TowerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkonow.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Normal Items.
        /// </summary>
        public static string UseNormalItems {
            get {
                return ResourceManager.GetString("UseNormalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use over limit item.
        /// </summary>
        public static string UseOverLimitItem {
            get {
                return ResourceManager.GetString("UseOverLimitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the battle log and parse it here.
        /// </summary>
        public static string You_can_download_the_battle_log_and_parse_it_here {
            get {
                return ResourceManager.GetString("You can download the battle log and parse it here", resourceCulture);
            }
        }
    }
}
